import "@/app/globals.css";
import Header from "@/components/header";
import { Toaster } from "sonner";


export const metadata = {
  title: "Pizzería",
  description: "Generated by create next app",
  manifest: "pwa/manifest.json"
};


export default function RootLayout({ children }) {
  return (

    <html lang="es">
      <body className={`antialiased min-h-screen`} >
        <Header />
        <main className="my-10 p-10">
          {children}
        </main>

        <Toaster position="top-right" richColors />
      </body>
    </html>

  );
}
